### ISSUE TITLE
[FABRIC] Old Chest Voxel doesn't work unless Old Chest is enabled

### ISSUE THREAD

**Issue by cdx78** [Adrenix/Nostalgic-Tweaks#31]
## Version Information

Minecraft Version: 1.19.3
Fabric Loader Version: 0.14.17
Fabric API Version: 0.76.0
Nostalgic Tweaks Version: v2.0.0 Beta-8.2

## Describe the Bug

The option for Old Chest Voxel won't activate unless Old Chest is also enabled. So you can't, for instance, have chests the way they were in Minecraft Beta 1.8 where the smaller model was used, but it still counted as a full block.

## Crash Report

N/a

## Bug Context

Enabled the setting for Old Chest Voxel, created a new world, placed down a chest, and stood on it to test the hitbox.

**Comment by Adrenix** [comment]
This is actually intentional. Telling the game a chest is a full block without using a full block model will cause rendering issues. You can turn off the old chest tweak and add chest blocks to the custom full block outlines list (`Eye Candy > Block Candy > Hitbox Outline`). This won't change the hitbox itself but will show the black block outline border around chests. Hopefully this helps.
