### ISSUE TITLE
[FORGE] Game crashing at startup

### ISSUE THREAD

**Issue by PlatFrog** [Adrenix/Nostalgic-Tweaks#40]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.20
Forge Version: 46.0.14
Nostalgic Tweaks Version: 2.0.0 Beta 8.4

## Describe the Bug
> A clear and concise description of what the bug is (e.g., startup crash, runtime crash, or something not working as intended).

I have a startup crash . I get java.lang.RuntimeException: null after trying to launch the game

## Crash Report
> https://pastebin.com/TKPMTFbi

## Bug Context
> If applicable, add some context to the bug. If a crash occurred while you were in-game, what happened before the crash? For example, "I fell from a high place and before the hurt sound could play the game crashed."

n/a

## Screenshots
> If applicable, add screenshots to help explain your problem.

![image](https://github.com/Adrenix/Nostalgic-Tweaks/assets/108823060/bc9baea8-e757-49a8-977c-0d7f09a23b9c)

**Comment by forkiesassds** [comment]
Might be a Forge issue. Since I don't see the issue is directly related with NT, have you tried updating Forge?

**Comment by Adrenix** [comment]
Thank you for submitting the crash log, but I don't see an indication that Nostalgic Tweaks is at fault. The crash log states that `More Doors` and `Traveler's Backpack` encountered an error during the `common_setup` event phase. Does the game start without Nostalgic Tweaks installed? If it does, then rerun with Nostalgic Tweaks installed and after the crash please provide the `.minecraft/logs/debug.log` file. Otherwise, if possible, update to 1.20.1 since that is what's currently being supported by most mods.
