### ISSUE TITLE
[FABRIC] Makes Bumblezone super dark by not respecting the ambient lighting values in the dimension type

### ISSUE THREAD

**Issue by TelepathicGrunt** [Adrenix/Nostalgic-Tweaks#68]
## Version Information

Minecraft Version: 1.20.1
Fabric Loader Version: 0.92.2
Fabric API Version: 0.15.11
Nostalgic Tweaks Version: 2.0.0-Beta-8.4.1

## Describe the Bug

Nostalgic Tweaks does not respect the ambient lighting value that modded dimensions may have. For Bumblezone, it is this value here:

https://github.com/TelepathicGrunt/Bumblezone/blob/1a354fdb15d2c517e174a56a6274a9fb661f5617/common/src/main/resources/data/the_bumblezone/dimension_type/the_bumblezone.json#L5

You can quickly enter my dimension by doing `/execute in the_bumblezone:the_bumblezone run tp ~ 90 ~`

## Screenshots

What the bugged look of my dimension is with Nostalgic Tweaks:
![image](https://github.com/Adrenix/Nostalgic-Tweaks/assets/40846040/21438c35-2107-4bbd-a293-784956b7537c)

What it is supposed to look like (Nostalgic Tweaks removed):
![image](https://github.com/Adrenix/Nostalgic-Tweaks/assets/40846040/5d44ccff-8246-4ae9-a49e-eb525f9500bd)

![image](https://github.com/Adrenix/Nostalgic-Tweaks/assets/40846040/77bdebaf-51c0-4213-945a-0b511dd71b0e)

**Comment by TelepathicGrunt** [comment]
Turning on this value fixes the issue
![image](https://github.com/Adrenix/Nostalgic-Tweaks/assets/40846040/0bcd62f8-d0a1-400a-ab14-3f39de85b57d)

However, I still consider it a bug that Nostalgic Tweaks does not respect the Dimension Type ambient lighting value for datapack/modded dimensions.

**Comment by Adrenix** [comment]
This was definitely an oversight on my part. The `Old Classic Light Rendering` forces the lightmap to be full-bright, which is why turning that on made everything look like it should. I added ambient lighting into the old lighting brightness calculation. The result is not as bright as the "expected" screenshot, but the old lighting was famously very dark. 
![image](https://github.com/Adrenix/Nostalgic-Tweaks/assets/15348635/61edbdaf-f2f7-4a5f-a2d1-6329da49f109)
The old lighting can be made brighter by setting `Disable Vanilla Brightness` to disabled, which will let the brightness setting in the video settings impact the light texture map again.
![image](https://github.com/Adrenix/Nostalgic-Tweaks/assets/15348635/e9a642c6-4fea-47ec-ab0c-295f1b28e2b9)
Thank you for the report and screenshots, this is a very cool dimension/mod!

**Comment by Adrenix** [comment]
This issue is resolved in beta 9 for 1.20.1. Thank you for submitting this!
